# Site settings
title: "Ameya Sinha"
email: ameyasinha26@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: ""
title_description: "Computer Science Undergraduate at Bits Pilani KK Birla Goa Campus.<br> Reader | Coder | Runner"
title_image: "https://avatars0.githubusercontent.com/u/20975496?s=400&v=4"
google_analytics: "UA-129019216-1"
disqus_account: ameyasinha
github_repository: https://github.com/ameyanator/ameyanator.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 7

# Social usernames/URLs
twitter_username: luva1900
github_username:  ameyanator
instagram_username: ameyanator26
reddit_username: ameyanator
linkedin_link: https://www.linkedin.com/in/ameya-sinha-8a629012a/
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/6871012/ameya-sinha
xing_link:
facebook_link: https://www.facebook.com/ameyanator
gmail_link: ameyasinha26@gmail.com
CV_link: https://drive.google.com/file/d/1HI1YfRm76Qnfkl77FjMKf4tgtioEBOvG/view

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
