# Site settings
title: "Ameya Sinha"
email: ameyasinha26@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "Computer Science Undergraduate at Bits Pilani KK Birla Goa Campus.<br> Reader | Coder | Runner"
title_image: "https://avatars0.githubusercontent.com/u/20975496?s=400&v=4"
google_analytics: "UA-20365477-4"
#disqus_account: ameyasinha
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: luva1900
github_username:  ameyanator
instagram_username: ameyanator26
reddit_username: ameyanator
linkedin_link: https://www.linkedin.com/in/ameya-sinha-8a629012a/
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/6871012/ameya-sinha
xing_link:
facebook_link: https://www.facebook.com/ameyanator

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
